coverage issue fixed

diff --git a/melos.yaml b/melos.yaml
--- a/melos.yaml
+++ b/melos.yaml
@@ -23,14 +23,12 @@ scripts:
     description: Runs flutter test on all packages.
     run: |
       flutter test --coverage .
-      lcov --summary coverage/lcov.info | grep "lines.......";
-      #COVERAGE=\$(lcov --summary coverage/lcov.info | grep "lines.......:" | awk '{print \$2}' | sed 's/%//');
-      #echo "coverage \\$COVERAGE";
-      # if (( \$(echo "\$COVERAGE < 80" | bc -l) )); then
-      #   echo "❌ Test coverage is below 80%. Failing the check."
-      #   exit 1
-      # else
-      #   echo "✅ Test coverage meets the requirement. Expected: 80%. Actual: \$COVERAGE%"
-      # fi
+      COVERAGE=\$(lcov --summary coverage/lcov.info | grep "lines......." | awk '{print \$2}' | sed 's/%//');
+      if (( \$(echo "\$COVERAGE < 80" | bc -l) )); then
+        echo "❌ Test coverage is below 80%. Failing the check."
+        exit 1
+      else
+        echo "✅ Test coverage meets the requirement. Expected: 80%. Actual: \$COVERAGE%"
+      fi
     exec:
       concurrency: 1
