Added categories screen

diff --git a/melos.yaml b/melos.yaml
--- a/melos.yaml
+++ b/melos.yaml
@@ -25,10 +25,23 @@ scripts:
       flutter test --coverage .
       COVERAGE=\$(lcov --summary coverage/lcov.info | grep "lines......." | awk '{print \$2}' | sed 's/%//');
       if awk "BEGIN {exit !(\$COVERAGE < 80)}"; then
-        echo "❌ Test coverage is below 80%. Failing the check."
+        echo "❌ Test coverage is below 80%. Current coverage is \$COVERAGE%. Failing the check."
         exit 1
       else
         echo "✅ Test coverage meets the requirement. Expected: 80%. Actual: \$COVERAGE%"
       fi
+    exec:
+      concurrency: 1
+  generate:
+    name: Generate
+    description: Runs build_runner on all packages.
+    run: |
+      grep -q "build_runner" pubspec.yaml && dart run build_runner build --delete-conflicting-outputs || echo "Skipping build_runner in $MELOS_PACKAGE_NAME"
+    exec:
+      concurrency: 1
+  clean-all:
+    name: Clean
+    description: Removes all generated files.
+    run: rm -rf .dart_tool build coverage coverage.html
     exec:
       concurrency: 1
